const products = [
  {
    id: 1,
    image: './assets/продукт1.jpg',
    title: 'Футболка белая Oversize',
    price: 799,
    category: 3,
    quantity: 1,
  },
  {
    id: 2,
    image: '/public/assets/продукт2.jpg',
    title: 'Футболка чёрная Minimal',
    price: 849,
    category: 3,
    quantity: 1,
  },
  {
    id: 3,
    image: './assets/продукт3.jpg',
    title: 'Куртка Classic',
    price: 1299,
    category: 5,
    quantity: 1,
  },
  {
    id: 4,
    image: './assets/продукт4.jpg',
    title: 'Свитшот синий Urban',
    price: 1149,
    category: 5,
    quantity: 1,
  },
  {
    id: 5,
    image: './assets/продукт5.jpg',
    title: 'Джоггеры чёрные Basic',
    price: 999,
    category: 4,
    quantity: 1,
  },
  {
    id: 6,
    image: './assets/продукт6.jpg',
    title: 'Куртка бежевая Light',
    price: 1699,
    category: 5,
    quantity: 1,
  },
  {
    id: 7,
    image: './assets/продукт7.jpg',
    title: 'Штаны серые Comfort',
    price: 749,
    category: 4,
    quantity: 1,
  },
  {
    id: 8,
    image: './assets/продукт8.jpg',
    title: 'Карго штаны хаки',
    price: 1199,
    category: 4,
    quantity: 1,
  },
  {
    id: 9,
    image: './assets/продукт9.jpg',
    title: 'Лонгслив белый Slim',
    price: 899,
    category: 3,
    quantity: 1,
  },
];

export default products;
